[package]
name = "coordinator1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "coordinator1"

[dependencies]
hdk = { workspace = true }
integrity = { workspace = true }
serde = { version = "1.0.203", features = ["derive"] }
