[package]
name = "coordinator2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "coordinator2"

[dependencies]
hdk = { workspace = true }
integrity = { workspace = true }
