[workspace]
members = ["coordinator1", "coordinator2", "integrity"]
resolver = "2"

[workspace.dependencies]
hdi = "0.7.0-dev.17"
hdk = "0.6.0-dev.20"
holochain_serialized_bytes = "*"
serde = "1.0"

integrity = { path = "integrity" }
