name: "test"

on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    name: fmt, clippy and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: Swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Doc
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc
      - name: Package fixture
        run: |
          nix develop -c ./fixture/package.sh
      - name: Run tests
        env:
          RUST_LOG: warn,holochain_http_gateway=info,zome_call=info
        run: cargo test --no-fail-fast -- --test-threads=1

  changelog-preview-comment:
      name: Add comment of changelog preview
      uses: holochain/actions/.github/workflows/changelog-preview-comment.yml@v1.3.0

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs: [checks]
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
