name: "test"

on:
  push:
    branches: [main]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    name: fmt, clippy and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Package fixture
        run: |
          nix develop -c ./fixture/package.sh
      - name: Run tests
        run: cargo test --no-fail-fast -- --test-threads=1

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs: [checks]
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
